{
	"header": {
		"line": "CVE-2021-3629 (A flaw was found in Undertow. A potential security issue in flow contr ...)",
		"name": "CVE-2021-3629",
		"description": "(A flaw was found in Undertow. A potential security issue in flow contr ...)"
	},
	"annotations": [
		{
			"line": "\t- undertow 2.2.12-1 (bug #1016448)",
			"type": "package",
			"package": "undertow",
			"kind": "fixed",
			"version": "2.2.12-1",
			"flags": [
				{
					"bug": 1016448
				}
			]
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1977362",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=1977362"
		},
		{
			"line": "\tNOTE: Make sure to also address followup tracked as CVE-2022-1259:",
			"type": "NOTE",
			"description": "Make sure to also address followup tracked as CVE-2022-1259:"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2072339",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=2072339"
		}
	]
}
