{
	"header": {
		"line": "CVE-2019-15486 (django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_ ...)",
		"name": "CVE-2019-15486",
		"description": "(django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_ ...)"
	},
	"annotations": [
		{
			"line": "\t- django-js-reverse <not-affected> (Issue introduced in 0.9.0)",
			"type": "package",
			"package": "django-js-reverse",
			"kind": "not-affected",
			"description": "Issue introduced in 0.9.0"
		},
		{
			"line": "\tNOTE: https://github.com/ierror/django-js-reverse/pull/81",
			"type": "NOTE",
			"description": "https://github.com/ierror/django-js-reverse/pull/81"
		},
		{
			"line": "\tNOTE: https://github.com/ierror/django-js-reverse/commit/a3b57d1e4424e2fadabcd526d170c4868d55159c (0.9.1)",
			"type": "NOTE",
			"description": "https://github.com/ierror/django-js-reverse/commit/a3b57d1e4424e2fadabcd526d170c4868d55159c (0.9.1)"
		}
	]
}
