{
	"header": {
		"line": "CVE-2024-8445 (The fix for CVE-2024-2199 in 389-ds-base was insufficient to cover all ...)",
		"name": "CVE-2024-8445",
		"description": "(The fix for CVE-2024-2199 in 389-ds-base was insufficient to cover all ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-4021-1}",
			"type": "xref",
			"bugs": [
				"DLA-4021-1"
			]
		},
		{
			"line": "\t- 389-ds-base <unfixed> (bug #1082852)",
			"type": "package",
			"package": "389-ds-base",
			"kind": "unfixed",
			"flags": [
				{
					"bug": 1082852
				}
			]
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2310110",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=2310110"
		},
		{
			"line": "\tNOTE: CVE exists because of an insufficent/incomplete fix for CVE-2024-2199",
			"type": "NOTE",
			"description": "CVE exists because of an insufficent/incomplete fix for CVE-2024-2199"
		}
	]
}
