{
	"header": {
		"line": "CVE-2020-27619 (In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)",
		"name": "CVE-2020-27619",
		"description": "(In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)"
	},
	"annotations": [
		{
			"line": "\t- python3.9 3.9.1~rc1-1 (unimportant)",
			"type": "package",
			"package": "python3.9",
			"kind": "fixed",
			"version": "3.9.1~rc1-1",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\t- python3.8 <removed> (unimportant)",
			"type": "package",
			"package": "python3.8",
			"kind": "removed",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\t- python3.7 <removed> (unimportant)",
			"type": "package",
			"package": "python3.7",
			"kind": "removed",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\t- python2.7 <removed> (unimportant)",
			"type": "package",
			"package": "python2.7",
			"kind": "removed",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\t- pypy3 7.3.5+dfsg-2",
			"type": "package",
			"package": "pypy3",
			"kind": "fixed",
			"version": "7.3.5+dfsg-2"
		},
		{
			"line": "\tNOTE: https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html",
			"type": "NOTE",
			"description": "https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (v3.9.1rc1)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (v3.9.1rc1)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (3.8)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (3.8)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (3.7)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (3.7)"
		},
		{
			"line": "\tNOTE: https://bugs.python.org/issue41944",
			"type": "NOTE",
			"description": "https://bugs.python.org/issue41944"
		},
		{
			"line": "\tNOTE: Only affects the testsuite",
			"type": "NOTE",
			"description": "Only affects the testsuite"
		}
	]
}
